### ISSUE TITLE
Lack of Memory Issue

### ISSUE THREAD

**Issue by sydneyschmitter** [sydneyschmitter/salmon_ag#3]
https://github.com/sydneyschmitter/salmon_ag/blob/4d6d4a96e2f53e2fec3aba45ba84cdb1f1750879/recreationsalmonidag.Rmd#L766

Hi All, I'm encountering a similar issue to Braeden with running any code that falls below this line. I've done some troubleshooting to expand the memory settings of my computer but they have not worked since yesterday. I'll go ahead and put the relevant .csv file, etc. in a folder in our Google Drive  under "2021 data" if you want to give it a try on your computer Lisa.

**Comment by lpfeif** [comment]
Could you describe how you changed things to overcome the first memory issue here, so that we can go back to it? 
Then if you think it is closed you could close the issue, or, you could have put your request (Issue # 6) here in this thread since it is the same issue at a different spot. Just a request for next time and to keep things organized.

**Comment by sydneyschmitter** [comment]
To overcome this issue I eliminated any potential unnecessary steps in the code. Specifically, I removed the updatenamesCDL function and altered crop groupings to go off of number codes for each crop type rather than strings. Essentially, this eliminated a "double name change" step.
